import SszProofConstructionRefinementCore
import SszIndicesFrontierSemantic

set_option autoImplicit false

namespace SszNative.Proof

/-- Construction reads the branch generated by the checked index subsystem;
there is no added claimed-node read or successful-future-read hypothesis. -/
theorem buildProof_refines (desc : Codec.Desc) (value : Codec.Value) (index : NatOperand)
    (arena : Delimited.ArenaState) (safe : HashLayout.SafeWidths desc)
    (descPhysical : desc.Physical) (valuePhysical : value.Physical)
    (indexPhysical : index.words.length < 2^64) :
    Refines (fun slice values => slice.values = values) (buildProof desc value index arena)
      (Ssz.buildProof desc.erase value.erase index.value) := by
  unfold buildProof Ssz.buildProof
  apply ResultRefines.bind_success (fun slice values => slice.values.map NatOperand.value = values)
    (fun slice values => slice.values = values) _ _ _ _
    (liftIndices_frontier_refines arena
      (Indices.branchIndices index arena.base arena.capacity arena.used) _
      (Indices.branchIndices_refines index arena.base arena.capacity arena.used indexPhysical))
  intro branches logical success same used
  have childSuccess := liftIndices_success arena
    (Indices.branchIndices index arena.base arena.capacity arena.used) branches success
  have physical := Indices.branchIndices_success_physical index arena.base arena.capacity arena.used
    branches childSuccess
  rw [← same]
  exact reserveHashRoots_refines desc value branches.values { arena with used := used }
    safe descPhysical valuePhysical physical

/-- Helper order is descending numeric order inherited from the index theorem;
empty helpers reserve an empty Hash slice without reading the schema or value. -/
theorem buildMultiproof_refines (desc : Codec.Desc) (value : Codec.Value)
    (indices : List NatOperand) (arena : Delimited.ArenaState)
    (safe : HashLayout.SafeWidths desc) (descPhysical : desc.Physical)
    (valuePhysical : value.Physical)
    (indicesPhysical : ∀ index ∈ indices, index.words.length < 2^64) :
    Refines (fun slice values => slice.values = values) (buildMultiproof desc value indices arena)
      (Ssz.buildMultiproof desc.erase value.erase (indices.map NatOperand.value)) := by
  unfold buildMultiproof Ssz.buildMultiproof
  apply ResultRefines.bind_success (fun slice values => slice.values.map NatOperand.value = values)
    (fun slice values => slice.values = values) _ _ _ _
    (liftIndices_frontier_refines arena
      (Indices.helperIndices indices arena.base arena.capacity arena.used) _
      (Indices.helperIndices_refines indices arena.base arena.capacity arena.used indicesPhysical))
  intro helpers logical success same used
  have childSuccess := liftIndices_success arena
    (Indices.helperIndices indices arena.base arena.capacity arena.used) helpers success
  have physical := Indices.helperIndices_success_physical indices arena.base arena.capacity arena.used
    helpers childSuccess
  rw [← same]
  exact reserveHashRoots_refines desc value helpers.values { arena with used := used }
    safe descPhysical valuePhysical physical

end SszNative.Proof
